### PR TITLE
sets background color of audio player's tab

### PR DESCRIPTION
**Pull request by kzidane**

### CODE REVIEW

**Comment by kzidane** [comment]
@danallan is [ba17582](https://github.com/cs50/harvard.cs50.audioplayer/pull/3/commits/ba175829ef5a28b0914629b44739d47cb6990f4c) better? hard-coding background color, as advised per [Cloud9 Theme](https://cloud9-sdk.readme.io/docs/creating-an-editor-plugin#section-cloud9-theme) and [adpoted by imgeditor](https://github.com/c9/c9.ide.imgeditor/blob/master/imgeditor.js#L585-L596), doesn't feel well. 

as mentioned, they're working on providing a better way, but until then, should we stick to ace's tab background? fyi, imgeditor's hard-coded colors don't match ace's tab background in all themes.

**Comment by danallan** [comment]
Looking good! One bug: if I use the Theme plugin to switch themes (View > Night mode), the tab doesn't change color correctly:
screen shot 2016-07-22 at 9 14 03 am

But if I open a new tab, it is colored correctly in both themes.

I also noticed that the code depends on the settings module, but doesn't use it. Maybe there's some code that relies on settings that addresses this that you might've forgotten to add to the commit?

I see what you mean about the imgeditor. It doesn't seem to be fully polished. For this audioplayer plugin, I wonder if the color transition from the tab color to the editor's bgcolor would be smoother if we had a small bar that matches the tab color, like the text editor does? For example:
screen shot 2016-07-22 at 9 23 23 am

vs
screen shot 2016-07-22 at 9 22 02 am

**Comment by kzidane** [comment]
@danallan oops! apologies for that! didn't have other CS50 plugins installed while fixing. just a couple of points:
- re the bug, this happens because our theme plugin changes the skin first, then ace's theme, so when layout's `themeChange` is fired, ace's theme is still the same, therefore tab's background color doesn't change immediately. this doesn't happen when changing theme from `View/Themes` because they do it the other way around.
  
  the problem is fixable by handling to ace's `themeChange` rather than layout's `themeChange`, which actually would make more sense, as it will preview theme on hovering items under `View/Themes` too. however, _sometimes_ I noticed a delay before background colors of the rest of the tabs change because our theme plugin does things the other way around.
- re bar, would it be sufficient to have the background color of the container the same as tab like this?
  
  audioplayer-dark
  
  otherwise, we'd probably have to create our own audio player, instead of using the browser's built-in, as the background color would be too dark in the dark theme like this
  
  audioplayer-darker
  
  we could still have a bar in the light theme, like this:
  
  audioplayer-lighter
  
  or to have the same as tab background like this:
  
  audioplayer-light
  
  thoughts?

**Comment by danallan** [comment]
I personally like the idea of having the background color match the tab color. Looks nice, and avoids the contrast issue with the player in the dark theme.

I'll raise an issue about the theme plugin. We should probably fix that to match the default behavior.

**Pull request merged**
